### ISSUE TITLE
When uploading/selecting file, clear text input. Similarly when typing, clear file upload field

### ISSUE THREAD

**Issue by gregsadetsky** [Garrett-Bodley/SHAlala#13]

**Comment by Garrett-Bodley** [comment]
I have it set up such that the SHA is a hash of `fileInput + textInput`. If either one is empty they get initialized as an empty `Uint8Array` and don't affect the SHA. I thought it'd be fun to be like "What does this file sound like?" and then go "What does this file sound like + my thoughts/notes/sentence/etc". But maybe it's better to keep the two distinct? 

Or maybe write something to make it clear that the two are being combined to generate the SHA?

**Comment by gregsadetsky** [comment]
Ah, I didn't get that! Yeah I think if it's clear it's a fun thing of either file, either text either both!
