### ISSUE TITLE
some notes seem to play longer even though the tempo is higher

### ISSUE THREAD

**Issue by gregsadetsky** [Garrett-Bodley/SHAlala#14]
shalala the "default" value of an empty string at 180 bpm and 240 bpm

the last two notes (of the short hash) feel longer at 240...? the 180bpm one end in a fast "ding ding" while the 240 bpm almost ends in a ~~dotted quarter note + quarter note??

**Comment by Garrett-Bodley** [comment]
Fixed: https://github.com/Garrett-Bodley/SHAlala/commit/d29012ac1b8110791d2fbadf041d74773dc2e55d
