### ISSUE TITLE
COULD WE PLEASE PLEASE PLEASE PLEASE HAVE INSTRUMENTS

### ISSUE THREAD

**Issue by gregsadetsky** [Garrett-Bodley/SHAlala#22]
https://nbrosowsky.github.io/tonejs-instruments/

https://nbrosowsky.github.io/tonejs-instruments/demo.html

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Garrett-Bodley** [comment]
this is incredible must have thank youuuu

**Comment by Garrett-Bodley** [comment]
Current build uses piano and bass! Want to migrate to React fully before adding a full "select your instrument" field. McCoy Tyner mode sounds much better

**Comment by Garrett-Bodley** [comment]
d7d6ac03bbc7e0d3a19dcd5359bd6167005251dd

Right now I'm just loading the samples directly from his github.io link. Is there a way to copy those files and serve them as part of Github pages? How did you serve the samples for sonic garbage?

**Comment by gregsadetsky** [comment]
Small note that it used to work on mobile but now I can't hear anything. Does it work on yours? Excited for react! Lmk if I can help

**Comment by Garrett-Bodley** [comment]
It works on my phone, but there's a significant delay. Instruments are implemented in an extremely hacky way rn. It reloads the samples every time you press the play button. Probably a network connection thing, maybe try waiting longer after pressing?

**Comment by Garrett-Bodley** [comment]
Oh also I turned the volume down for presentations. That might be part of it?

**Comment by gregsadetsky** [comment]
Yeah it does work now sorry. And you're right about the delay, I was also in a place w slowish mobile internet
